name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 815596
          sessionCookie: ${{ secrets.AOC_SESSION }}
          leaderboardId: 322255
          year: 2021
          headerPrefix: "###"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
